server:
  port: 8080

spring:
  application:
    name: smartgrow-service

  security:
    user:
      name: hoang
      password: 123456

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        default_schema: iot_service
    show-sql: true

  datasource:
    hikari:
      connection-timeout: 15000
      schema: iot_service
      maximum-pool-size: 15
      minimum-idle: 1
    driver-class-name: org.postgresql.Driver

  http:
    converters:
      string-encoding-charset: UTF-8

auth-token:
  secret: ${JWT_SECRET} # Base64
  access_token_ttl: 60 # min
  refresh_token_ttl: 43200 # min