server:
  port: 8080

spring:
  application:
    name: jobfinder-service

  security:
    user:
      name: hoang
      password: 123456

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        default_schema: jobspot_service
    show-sql: true

  datasource:
    hikari:
      connection-timeout: 15000
      schema: jobspot_service
      maximum-pool-size: 15
      minimum-idle: 1
      data-source-properties:
        prepareThreshold: 0
    driver-class-name: org.postgresql.Driver

  jackson:
    mapper:
      sort-properties-alphabetically: false

springdoc:
  api-docs:
    path: "/api/v1/api-docs"
  swagger-ui:
    path: "/api/v1/swagger-ui.html"

auth-token:
  jwt-secret: ${JWT_SECRET} # Base64
  access_token_ttl: 60 # min
  refresh_token_ttl: 43200 # min