spring:
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

supabase:
  s3:
    endpoint-url: ${SUPABASE_S3_ENDPOINT_URL}
    region: "ap-southeast-1"
    access-key-id: ${SUPABASE_S3_KEY_ID}
    secret-access-key: ${SUPABASE_SECRET_ACCESS_KEY}
    public-bucket-name: "public-job-finder-bucket"
    private-bucket-name: "private-job-finder-bucket"
    public-asset-link: "https://${SUPABASE_PROJECT_ID}.supabase.co/storage/v1/object/public/public-job-finder-bucket"